android:
  build:
    package: appbundle
  version:
    value: 0.0.1+1250809
    format: 1yyMMdd
    autoIncrement: true

# Deneme
web:
  build:
    package: web
  version:
    value: 0.0.1+0
    format: 1yyMMdd
    autoIncrement: false
ios:
  build:
    package: ipa
  version:
    value: 0.0.1+0
    format: 1yyMMdd
    autoIncrement: false
macos:
  build:
    package: macos
  version:
    value: 0.0.1+0
    format: 1yyMMdd
    autoIncrement: false
windows:
  build:
    package: windows
  version:
    value: 0.0.1+0
    format: 1yyMMdd
    autoIncrement: false
linux:
  build:
    package: linux
  version:
    value: 0.0.1+0
    format: 1yyMMdd
    autoIncrement: false