name: app_tools
description: A sample command-line application.
version: 1.0.0+1240827

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

executables:
  app_build:
  app_reinstall: