name: app_tools
description: A sample command-line application.
version: 1.1.0+65

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  very_good_analysis: ^9.0.0

executables:
  atbuild:
  atclean: