name: app_tools
description: A sample command-line application.
version: 1.0.0+4

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  collection: ^1.19.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  atbuild:
  atclean: