name: app_tools
description: A sample command-line application.
version: 1.0.0+15

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  freezed_annotation: ^2.4.4
  intl: ^0.20.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0

executables:
  atbuild:
  atclean: